### ISSUE TITLE
Cannot Update Configuration, VPN wont work

### ISSUE THREAD

**Issue by mcordes92** [eduardogsilva/wireguard_webadmin#19]
I created a new Instance and then come the Error in den Picture, by every Update for the WG configuration come the same error. I restartet the Container then come the error from the other Picture

![2024-03-28 10_58_27-Portainer _ local – Mozilla Firefox](https://github.com/eduardogsilva/wireguard_webadmin/assets/93989308/61cf6948-8722-4a3f-8a6e-b59ada2e8518)

![2024-03-28 10_56_23-](https://github.com/eduardogsilva/wireguard_webadmin/assets/93989308/c1cd81f4-ea45-4ad7-8082-292e8ef7897e)

**Comment by eduardogsilva** [comment]
Hello @mcordes92 , looks like your host kernel does not have the wireguard modules loaded.
Even using a docker container, you need these modules on the host.

I can be wrong, but maybe it's an older kernel.
Can you please run the following commands on the host machine and paste the output here?

`uname -a`
`cat /etc/issue`
`modprobe wireguard`

**Comment by mcordes92** [comment]
Thank you

**Comment by eduardogsilva** [comment]
If you need anything else, let me know 😉
